#!/bin/sh
#
# @name VTOL Albatross
#
# @type Plane A-Tail
# @class Plane
#
# @output MAIN1 aileron right
# @output MAIN2 aileron left
# @output MAIN3 v-tail right
# @output MAIN4 v-tail left
# @output MAIN5 Motor 1
# @output MAIN6 Motor 2
# @output MAIN7 Motor 3
# @output MAIN8 Motor 4
#
# @output AUX1 throttle
# @output AUX2 feed-through of RC AUX2 channel
# @output AUX3 feed-through of RC AUX3 channel
#
# @maintainer Andreas Antener <andreas@uaventure.com>
#

sh /etc/init.d/rc.vtol_defaults

if [ $AUTOCNF = yes ]
then
	param set FW_AIRSPD_MIN 13
	param set FW_AIRSPD_TRIM 19
	param set FW_AIRSPD_MAX 30

	param set FW_MAN_P_MAX 55
	param set FW_MAN_R_MAX 55
	param set FW_R_LIM 55

	param set FW_WR_FF 0.2
	param set FW_WR_I 0.3
	param set FW_WR_IMAX 0.8
	param set FW_WR_P 1
	param set FW_W_RMAX 30

	param set MC_PITCHRATE_I	0.2
	param set MC_PITCHRATE_MAX 60
	param set MC_ROLLRATE_I	0.2
	param set MC_ROLLRATE_MAX 60
	param set MC_YAWRATE_I 0.15
	param set MC_YAWRATE_MAX 40
	param set MC_YAWRATE_P 0.3

	# set disarmed value for the ESC
	param set PWM_DISARMED 1000

	#VTOL Params
	param set MIS_TAKEOFF_ALT 20


fi

set MAV_TYPE 22

set MIXER VTOLAlbatross
set MIXER_AUX VTOLAlbatross
# use PWM parameters for throttle channel
set PWM_OUT 5678
